### ISSUE TITLE
error: to generate dependencies you must specify either -M or -MM

### ISSUE THREAD

**Issue by boitumeloruf** [tulipp-eu/sthem#11]
When trying to make bin for a project in which the hw fucntion is distributed over mutliple src files following error occurs:

`
aarch64-none-elf-g++ -E -I/home/rufboi/sdx_workspace/tulipp-sgmstereo-ultrascale-cl/src -I/home/rufboi/sdx_workspace/tulipp-sgmstereo-ultrascale-cl/src//home/rufboi/sdx_workspace//tulipp-sgmstereo-ultrascale-cl/src -I/home/rufboi/sdx_workspace/tulipp-sgmstereo-ultrascale-cl/src//home/rufboi/sdx_workspace//tulipp-sgmstereo-ultrascale-cl/pfm/emc2_cameraLink/sw/arm-xilinx-eabi/include -fmessage-length=0 -DBUILD_STEREO -DHALF_ENABLE_CPP11_CMATH=0 -D __SDSCC__ -MT/home/rufboi/.tulipp/tulipp-sgmstereo-ultrascale-cl/stereo.o    -I /home/rufboi/sdx_workspace/tulipp-sgmstereo-ultrascale-cl/pfm/emc2_cameraLink_200MHz/sw/arm-xilinx-eabi/include  -I /opt/Xilinx/SDx/2017.2/target/aarch64-none/include  -I /opt/Xilinx/SDx/2017.2/Vivado_HLS/include /home/rufboi/sdx_workspace/tulipp-sgmstereo-ultrascale-cl/src/stereo/stereo.cpp -o /home/rufboi/.tulipp/tulipp-sgmstereo-ultrascale-cl/_sds/.pp/stereo.ii
cc1plus: error: to generate dependencies you must specify either -M or -MM
`

**Comment by djupdal** [comment]
I can't reproduce this.  I am using SDSoC 2018.2, are you on 2017.2?  I will try 2017.2 tomorrow.

**Comment by boitumeloruf** [comment]
Yes, I am with 2017.2. For my application I could do a workaround if you are not able to reproduce.

**Comment by djupdal** [comment]
I managed to reproduce the bug.  Should be fixed now.

**Comment by boitumeloruf** [comment]
Yes. Thanks.
