### ISSUE TITLE
Warnings when installing on UBUNTU 18.04

### ISSUE THREAD

**Issue by nikmehr** [tulipp-eu/sthem#13]
Hi,

I am trying to install the tool on UBUNTU 18.04. Running make gives me a few warnings as:

`clang++ -fno-rtti -O -g `llvm-config --cxxflags` tulipp_source_tool.cpp -Wl,--start-group -lclangAST -lclangASTMatchers -lclangAnalysis -lclangBasic -lclangDriver -lclangEdit -lclangFrontend -lclangFrontendTool -lclangLex -lclangParse -lclangSema -lclangEdit -lclangRewrite -lclangRewriteFrontend -lclangStaticAnalyzerFrontend -lclangStaticAnalyzerCheckers -lclangStaticAnalyzerCore -lclangSerialization -lclangToolingCore -lclangTooling -lclangFormat -Wl,--end-group `llvm-config --ldflags --libs --system-libs` -o tulipp_source_tool
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]`

and

`clang++ -std=gnu++11 -fno-rtti -O -g `llvm-config --cxxflags` -c src/llvm_ir_parser.cpp -o llvm_ir_parser.o
clang: warning: -Wl,--no-keep-files-mapped: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--no-map-whole-files: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]`

and

`clang++ -std=gnu++11 -fno-rtti -O -g `llvm-config --cxxflags` -c src/cfg.cpp -o cfg.o
clang: warning: -Wl,--no-keep-files-mapped: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: -Wl,--no-map-whole-files: 'linker' input unused [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-fuse-ld=gold' [-Wunused-command-line-argument]
warning: unknown warning option '-Wno-maybe-uninitialized'; did you mean '-Wno-uninitialized'? [-Wunknown-warning-option]`.

Should I get worried about the warnings? Any suggestion?

Regards
Hooman

**Comment by djupdal** [comment]
No need to get worried.  Those are normal.
