### ISSUE TITLE
Make console interface not requiring x-server

### ISSUE THREAD

**Issue by bgottschall** [tulipp-eu/sthem#15]
When using analysis utility via console on a system without an x-server, QT is complaining about a missing desktop and denies execution.

> qt.qpa.screen: QXcbConnection: Could not connect to display :0
> Could not connect to any X display.

**Comment by djupdal** [comment]
Try adding the following on the command line:
--platform offscreen

**Comment by magnusjahre** [comment]
Did this solve your problem Björn? If so, can you close the issue?

**Comment by bgottschall** [comment]
yes, thanks :+1:
